module.exports = {
  apps: [
    {
      name: 'next-brand-a',
      cwd: '/var/www/brand-a',
      script: 'node',
      args: '.next/standalone/server.js',
      exec_mode: 'cluster',
      instances: 2,
      env: {
        NODE_ENV: 'production',
        PORT: '3001',
        HOSTNAME: '127.0.0.1',
        NEXT_PUBLIC_SITE_URL: 'https://brand-a.com',
        NEXT_PUBLIC_SITE_NAME: 'Brand A Store',
        WC_STORE_URL: 'https://wp-brand-a.com/wp-json/wc/store/v1',
        WC_REST_URL: 'https://wp-brand-a.com/wp-json/wc/v3',
        WC_CONSUMER_KEY: 'ck_aaaaaaaaaaaaaaaaaaaaaaaaa',
        WC_CONSUMER_SECRET: 'cs_aaaaaaaaaaaaaaaaaaaaaaaaa',
        WC_WEBHOOK_SECRET: 'whs_brand_a_secret',
        REDIS_URL: 'redis://127.0.0.1:6379/0',
      },
      watch: false,
      max_memory_restart: '512M',
      out_file: '/var/log/pm2/brand-a-out.log',
      error_file: '/var/log/pm2/brand-a-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'next-brand-b',
      cwd: '/var/www/brand-b',
      script: 'node',
      args: '.next/standalone/server.js',
      exec_mode: 'cluster',
      instances: 2,
      env: {
        NODE_ENV: 'production',
        PORT: '3002',
        HOSTNAME: '127.0.0.1',
        NEXT_PUBLIC_SITE_URL: 'https://brand-b.com',
        NEXT_PUBLIC_SITE_NAME: 'Brand B Store',
        WC_STORE_URL: 'https://wp-brand-b.com/wp-json/wc/store/v1',
        WC_REST_URL: 'https://wp-brand-b.com/wp-json/wc/v3',
        WC_CONSUMER_KEY: 'ck_bbbbbbbbbbbbbbbbbbbbbbbbb',
        WC_CONSUMER_SECRET: 'cs_bbbbbbbbbbbbbbbbbbbbbbbbb',
        WC_WEBHOOK_SECRET: 'whs_brand_b_secret',
        REDIS_URL: 'redis://127.0.0.1:6379/1',
      },
      watch: false,
      max_memory_restart: '512M',
      out_file: '/var/log/pm2/brand-b-out.log',
      error_file: '/var/log/pm2/brand-b-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
}
